In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
def read_csv(file_path):
  df = pd.read_csv(file_path)
  X = np.array(df["sentence"])
  Y = np.array(df["label"], dtype=int)

  return X, Y

In [4]:
X_train, Y_train = read_csv("/content/dataset/train.csv")
X_test, Y_test = read_csv("/content/dataset/test.csv")

In [5]:
index = 5
X_train[index], Y_train[index]

('I love you mum', 0)

In [6]:
def label_to_emoji(label):
  emojies = ["❤️", "⚾️", "😄", "😔", "🍴"]
  return emojies[label]

In [7]:
index = 7
X_train[index], label_to_emoji(Y_train[index])

('congratulations on your acceptance', '😄')

In [8]:
unique, counts = np.unique(Y_train, return_counts=True)

print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [13]:
max_len = len(max(X_train, key=len).split(" "))
max_len

10

In [14]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2024-02-02 21:12:28--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2024-02-02 21:12:28--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.01MB/s    in 2m 39s  

2024-02-02 21:15:07 (5.17 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [15]:
!unzip -q glove.6B.zip -d glove.6B

In [16]:
f = open("/content/glove.6B/glove.6B.50d.txt", encoding="utf-8")

words_vector = {}
for line in f:
  line = line.strip().split()
  word = line[0]
  vector = np.array(line[1:], dtype=np.float64)
  words_vector[word] = vector

In [17]:
words_vector["snake"]

array([ 0.49251 , -0.24279 , -0.49748 ,  0.28443 ,  0.16984 ,  0.61016 ,
        0.20294 , -0.19734 ,  0.93474 , -0.11809 , -0.26342 ,  0.97142 ,
        1.0427  ,  0.60017 , -0.46936 ,  0.10087 ,  0.60649 ,  1.1277  ,
       -1.1823  , -0.29334 , -0.72885 , -0.46904 ,  1.1104  ,  0.27504 ,
        0.48043 , -1.3031  , -0.58713 ,  0.90264 ,  0.089552, -0.60348 ,
        1.1117  , -0.85367 , -0.13902 ,  0.87767 , -0.19307 ,  0.10299 ,
       -0.83688 , -0.87202 ,  0.46529 , -0.22325 , -0.49207 ,  0.33727 ,
       -0.49699 ,  0.95006 ,  0.75007 , -0.21252 ,  0.47244 , -1.4552  ,
        0.11704 , -0.61483 ])

In [18]:
words_vector["programming"]

array([ 0.14957 , -0.16036 , -0.1369  ,  1.0076  , -0.37291 ,  0.63466 ,
       -0.93203 , -1.5188  , -0.24924 ,  0.67075 ,  0.51193 ,  0.28389 ,
        0.18781 ,  0.8798  , -0.023971,  0.39789 , -0.72769 ,  1.0153  ,
        0.11723 , -0.14114 ,  0.974   ,  0.48037 ,  0.25464 ,  1.3262  ,
        0.17958 ,  0.19717 ,  0.074712, -0.24844 ,  0.26248 , -0.084427,
        3.156   ,  0.38308 , -0.095827, -0.99383 , -0.20497 ,  0.38918 ,
       -0.13281 , -0.21775 , -0.93632 ,  0.37943 ,  0.78475 ,  0.36969 ,
       -1.3904  ,  0.54891 , -1.3798  ,  0.18898 ,  0.60928 ,  0.98271 ,
       -0.53934 ,  1.4439  ])

In [19]:
def sentence_to_ave(sentence):
  sentence = sentence.lower()
  words = sentence.split(" ")

  sum_vectors = np.zeros((50, ))
  for word in words:
    sum_vectors += words_vector[word]

  ave_vector = sum_vectors / len(words)

  return ave_vector


In [20]:
sentence_to_ave("I love programming too much")

array([ 0.157256  ,  0.1669862 , -0.188816  , -0.27733   ,  0.316686  ,
        0.2276832 , -0.442016  , -0.19912792, -0.528786  ,  0.58095151,
       -0.099434  ,  0.543644  , -0.400818  , -0.0196456 ,  0.6553478 ,
        0.357032  ,  0.110736  ,  0.3904726 , -0.015683  , -0.5693798 ,
       -0.11808   ,  0.662674  ,  0.50238   ,  0.380024  ,  0.798924  ,
       -1.542946  , -0.8024376 ,  0.265944  ,  0.838432  , -0.497945  ,
        3.32178   ,  0.516902  , -0.0628614 , -0.236668  , -0.1666506 ,
       -0.104354  , -0.144238  ,  0.238698  , -0.116562  , -0.335334  ,
        0.00965334,  0.2257584 , -0.261848  ,  0.44801   , -0.2448288 ,
        0.1346956 ,  0.0192128 , -0.21776632, -0.28343   ,  0.698352  ])

In [ ]:
X_train_ave = []

for x_train in X_train:
  X_train_ave.append(sentence_to_ave(x_train))

X_train_ave = np.array(X_train_ave)