In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
def read_csv(file_path):
  df = pd.read_csv(file_path)
  X = np.array(df["sentence"])
  Y = np.array(df["label"], dtype=int)

  return X, Y

In [3]:
X_train, Y_train = read_csv("/content/dataset/train.csv")
X_test, Y_test = read_csv("/content/dataset/test.csv")

In [4]:
index = 5
X_train[index], Y_train[index]

('I love you mum', 0)

In [5]:
def label_to_emoji(label):
  emojies = ["❤️", "⚾️", "😄", "😔", "🍴"]
  return emojies[label]

In [20]:
index = 25
X_train[index], label_to_emoji(Y_train[index])

('The chicago cubs won again', '⚾️')

In [21]:
unique, counts = np.unique(Y_train, return_counts=True)

print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [22]:
max_len = len(max(X_train, key=len).split(" "))
max_len

10

In [23]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2024-02-03 19:52:40--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2024-02-03 19:52:40--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.02MB/s    in 2m 39s  

2024-02-03 19:55:19 (5.18 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [24]:
!unzip -q glove.6B.zip -d glove.6B

In [25]:
f = open("/content/glove.6B/glove.6B.50d.txt", encoding="utf-8")

words_vector = {}
for line in f:
  line = line.strip().split()
  word = line[0]
  vector = np.array(line[1:], dtype=np.float64)
  words_vector[word] = vector

In [26]:
words_vector["snake"]

array([ 0.49251 , -0.24279 , -0.49748 ,  0.28443 ,  0.16984 ,  0.61016 ,
        0.20294 , -0.19734 ,  0.93474 , -0.11809 , -0.26342 ,  0.97142 ,
        1.0427  ,  0.60017 , -0.46936 ,  0.10087 ,  0.60649 ,  1.1277  ,
       -1.1823  , -0.29334 , -0.72885 , -0.46904 ,  1.1104  ,  0.27504 ,
        0.48043 , -1.3031  , -0.58713 ,  0.90264 ,  0.089552, -0.60348 ,
        1.1117  , -0.85367 , -0.13902 ,  0.87767 , -0.19307 ,  0.10299 ,
       -0.83688 , -0.87202 ,  0.46529 , -0.22325 , -0.49207 ,  0.33727 ,
       -0.49699 ,  0.95006 ,  0.75007 , -0.21252 ,  0.47244 , -1.4552  ,
        0.11704 , -0.61483 ])

In [27]:
words_vector["programming"]

array([ 0.14957 , -0.16036 , -0.1369  ,  1.0076  , -0.37291 ,  0.63466 ,
       -0.93203 , -1.5188  , -0.24924 ,  0.67075 ,  0.51193 ,  0.28389 ,
        0.18781 ,  0.8798  , -0.023971,  0.39789 , -0.72769 ,  1.0153  ,
        0.11723 , -0.14114 ,  0.974   ,  0.48037 ,  0.25464 ,  1.3262  ,
        0.17958 ,  0.19717 ,  0.074712, -0.24844 ,  0.26248 , -0.084427,
        3.156   ,  0.38308 , -0.095827, -0.99383 , -0.20497 ,  0.38918 ,
       -0.13281 , -0.21775 , -0.93632 ,  0.37943 ,  0.78475 ,  0.36969 ,
       -1.3904  ,  0.54891 , -1.3798  ,  0.18898 ,  0.60928 ,  0.98271 ,
       -0.53934 ,  1.4439  ])

In [38]:
def sentence_to_ave(sentence):
  # try:
  sentence = sentence.lower()
  words = sentence.strip().split(" ")

  sum_vectors = np.zeros((50, ))
  for word in words:
    sum_vectors += words_vector[word]

  ave_vector = sum_vectors / len(words)

  return ave_vector
  # except:
  #   print(sentence)
  #   return None

In [32]:
sentence_to_ave("I love programming too much")

array([ 0.157256  ,  0.1669862 , -0.188816  , -0.27733   ,  0.316686  ,
        0.2276832 , -0.442016  , -0.19912792, -0.528786  ,  0.58095151,
       -0.099434  ,  0.543644  , -0.400818  , -0.0196456 ,  0.6553478 ,
        0.357032  ,  0.110736  ,  0.3904726 , -0.015683  , -0.5693798 ,
       -0.11808   ,  0.662674  ,  0.50238   ,  0.380024  ,  0.798924  ,
       -1.542946  , -0.8024376 ,  0.265944  ,  0.838432  , -0.497945  ,
        3.32178   ,  0.516902  , -0.0628614 , -0.236668  , -0.1666506 ,
       -0.104354  , -0.144238  ,  0.238698  , -0.116562  , -0.335334  ,
        0.00965334,  0.2257584 , -0.261848  ,  0.44801   , -0.2448288 ,
        0.1346956 ,  0.0192128 , -0.21776632, -0.28343   ,  0.698352  ])

In [39]:
X_train_ave = []

for x_train in X_train:
  X_train_ave.append(sentence_to_ave(x_train))

X_train_ave = np.array(X_train_ave)

X_train_ave.shape

(132, 50)

In [42]:
Y_train_one_hoted = tf.keras.utils.to_categorical(Y_train, num_classes=5)

In [43]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(5, input_shape=(50,), activation="Softmax")
])

In [45]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [47]:
model.fit(X_train_ave, Y_train_one_hoted, epochs=200)

Epoch 1/200
5/5 [==============================] - 0s 6ms/step - loss: 0.7913 - accuracy: 0.7576
Epoch 2/200
5/5 [==============================] - 0s 5ms/step - loss: 0.7902 - accuracy: 0.7652
Epoch 3/200
5/5 [==============================] - 0s 5ms/step - loss: 0.7886 - accuracy: 0.7652
Epoch 4/200
5/5 [==============================] - 0s 6ms/step - loss: 0.7869 - accuracy: 0.7727
Epoch 5/200
5/5 [==============================] - 0s 5ms/step - loss: 0.7853 - accuracy: 0.7727
Epoch 6/200
5/5 [==============================] - 0s 6ms/step - loss: 0.7833 - accuracy: 0.7652
Epoch 7/200
5/5 [==============================] - 0s 6ms/step - loss: 0.7815 - accuracy: 0.7652
Epoch 8/200
5/5 [==============================] - 0s 6ms/step - loss: 0.7797 - accuracy: 0.7652
Epoch 9/200
5/5 [==============================] - 0s 5ms/step - loss: 0.7786 - accuracy: 0.7652
Epoch 10/200
5/5 [==============================] - 0s 4ms/step - loss: 0.7767 - accuracy: 0.7727
Epoch 11/200
5/5 [===========

In [54]:
my_test_sentence = "I love see food"

my_test_ave = sentence_to_ave(my_test_sentence)
my_test_ave

array([ 0.19149   ,  0.39613   , -0.29437825, -0.45514   ,  0.58745   ,
       -0.1885175 , -0.4617425 , -0.1886249 , -0.0073275 ,  0.25208964,
       -0.0832225 ,  0.599987  , -0.2566225 , -0.22175525,  0.995455  ,
        0.4280425 ,  0.1588746 ,  0.07874   ,  0.100787  , -0.52995725,
       -0.06616   ,  0.483167  ,  0.57353   ,  0.3309475 ,  0.672675  ,
       -1.651235  , -1.045405  ,  0.13963   ,  0.9171275 , -0.46865   ,
        3.20685   ,  0.6419725 , -0.4071875 ,  0.08056   , -0.215035  ,
       -0.0615625 , -0.0311025 ,  0.1012125 ,  0.389025  , -0.22      ,
       -0.07731833,  0.165113  ,  0.0754775 ,  0.159702  ,  0.4388465 ,
        0.41323   , -0.135089  , -0.46333   , -0.0194825 ,  0.428735  ])

In [55]:
my_test_ave = np.array([my_test_ave])

result = model.predict(my_test_ave)
y_pred = np.argmax(result)
y_pred

1/1 [==============================] - 0s 25ms/step


4

In [56]:
label_to_emoji(y_pred)

'🍴'